### ISSUE TITLE
Traceback : ValueError: 35 is not a valid Verb 

### ISSUE THREAD

**Issue by niharmehta** [oyvindkinsey/avionmqtt#10]
this popped up on my console. Not sure what caused it. It was on a light I was testing, but have not yet recreated issue. I think the unknown Noun is more cosmetic .  Getting the same Unknown noun for Dates as well.   The verb error I am not sure what triggered it. 

On a possibly related note, as I have been testing this, for some reason my schedules and scenes have all disappeared from Avi-On App and web.  I know I have not actively done anything to wipe all my schedules / scenes from Avion app.. but.. they are gone suddenly. Any chance it could be related to avionmqtt ? I do have a RAB, but I think I remember that the lights keep the schedules on the devices.  

```
unknown noun Noun.SUNRISE_SUNSET
mesh: parsing notification ac-82-73-23-ff-0-0-0-10-4
mesh: parsing data b'#\xff\x00\x00\x00\x10\x04' from 33452
Task exception was never retrieved
future: <Task finished name='Task-687' coro=<mesh_subscribe.<locals>.cb() done, defined at /home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py:327> exception=ValueError('35 is not a valid Verb')>
Traceback (most recent call last):
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 333, in cb
    parsed = mesh_parse_command(decoded["source"], decoded["decpayload"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 316, in mesh_parse_command
    return mesh_parse_data(int.from_bytes(bytes([data[1], data[0]]), byteorder="big"), data[3:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 286, in mesh_parse_data
    verb = Verb(data[0])
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 35 is not a valid Verb
mesh: parsing notification ac-82-73-23-ff-0-0-0-f-4
mesh: parsing data b'#\xff\x00\x00\x00\x0f\x04' from 33452
Task exception was never retrieved
future: <Task finished name='Task-689' coro=<mesh_subscribe.<locals>.cb() done, defined at /home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py:327> exception=ValueError('35 is not a valid Verb')>
Traceback (most recent call last):
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 333, in cb
    parsed = mesh_parse_command(decoded["source"], decoded["decpayload"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 316, in mesh_parse_command
    return mesh_parse_data(int.from_bytes(bytes([data[1], data[0]]), byteorder="big"), data[3:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 286, in mesh_parse_data
    verb = Verb(data[0])
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 35 is not a valid Verb
mesh: parsing notification ac-82-73-23-ff-0-0-0-11-4
mesh: parsing data b'#\xff\x00\x00\x00\x11\x04' from 33452
Task exception was never retrieved
future: <Task finished name='Task-691' coro=<mesh_subscribe.<locals>.cb() done, defined at /home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py:327> exception=ValueError('35 is not a valid Verb')>
Traceback (most recent call last):
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 333, in cb
    parsed = mesh_parse_command(decoded["source"], decoded["decpayload"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 316, in mesh_parse_command
    return mesh_parse_data(int.from_bytes(bytes([data[1], data[0]]), byteorder="big"), data[3:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmehta/avionmqtt/lib/python3.11/site-packages/avionmqtt/__init__.py", line 286, in mesh_parse_data
    verb = Verb(data[0])
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 717, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1133, in __new__
    raise ve_exc
ValueError: 35 is not a valid Verb
```

**Comment by oyvindkinsey** [comment]
If you look at https://myaccount.avi-on.com/, do you see the scenes and schedules there?
I never really used these, but the ones I tested with do show up in the web app, but I too see that there's nothing in the app itself.  

I have been running this for a week without seeing any crashes (with a RAB), so I'm curious what could have caused all this. If this ended up undoing a lot of work you've put in, then I'm sorry about that - I hope the utility of this library will make up for that though.

Since the notification is visible in the trace above, I'll try to figure out what is going on. Do you have any other Avi-on devices in the mix? Sensors, or speakers etc?

**Comment by oyvindkinsey** [comment]
The unknown noun message is just informative - it's just that the noun is not handled. The not a valid verb issues is more difficult, since the existing list of verbs is pulled straight out of Avi-on's app. I'll take a look at how they handle this - I'm guessing they have values not actually present in the enum itself.

**Comment by niharmehta** [comment]
Schedules are gone form the Web interface as well as instances on the app on multiple devices.   Its ok, the utility of this bridge is far more valule  and having it controlled by HA was the ultimate goal regardless. This just moves up the schedule a bit sooner. 

 I only have the RAB and one of the single gang scene controllers .

The traceback has happened a couple of more times while navigating the app..  I am still testing to see exactly what actions i am doing when it triggers.

**Comment by oyvindkinsey** [comment]
b524eb92381325930acee1f19c41dc1ead112b54 adds graceful handling, will update pypip now.

**Comment by oyvindkinsey** [comment]
Ah, interesting - I will try with the scene controller, it's rarely used now that I have this integrated with HA.

What device is 33452? That's where this is coming from.

**Comment by niharmehta** [comment]
In that error, it was one of the lights I was testing in the app (not HA).  However i also had the error on 33445. So its not limited to a single light.  I will update to the latest version next.

**Comment by niharmehta** [comment]
i don't use the scene controller much either, but it is there for local control. Since its battery, I think its entirely silent until a button is pushed.

**Comment by niharmehta** [comment]
I have rarely used the web app over the years.  Even with the RAB, I have had inconstancy  and some serious delays. When both my mobile devices/tablets are connected via BLE , controls in either direction across the bridge is reflected within a second or so on the other controllers.  This is becoming so much a better experience already .

**Comment by oyvindkinsey** [comment]
@niharmehta , did you ever figure out what this was? 
The java logic has some conditionals around the original logic, which was really hard to grok, so I'm going to chalk this up to a missing conditional. For now, we're catching and handling this, so should be fine. Future iterations might handle this more explicitly.

**Comment by niharmehta** [comment]
never could figure out how to predictably recreate.  I was just clicking around the app and it would pop up in the log.  Using just the HA interface and the bridge, I have not see it pop up yet.
