### ISSUE TITLE
Best way to identify PRODUCT_NAMES numbers?

### ISSUE THREAD

**Issue by deadman96385** [oyvindkinsey/avionmqtt#12]
I was thinking about this and I know theres a way to pull down the api response for AVI-On and it includes the number somewhere in there. Do you know of a faster way to do it?

**Comment by oyvindkinsey** [comment]
The product_id is already used for the entity name if the product _id is unknown, so this should already be covered. 
I'll look at how the native app does name and capability resolution, and see if we can't copy that.

**Comment by oyvindkinsey** [comment]
Is this issue about identifying what the product_id is, or about resulting the name for a given product_id?

**Comment by deadman96385** [comment]
I should have tried adding some of the others to see what happens before going down the rabbit hole. Your right with it putting the number in. 

[Light Adapter](https://www.cooperlighting.com/global/brands/halo-home/1024966/halo-home-smart-light-adapter-hwad) ID = 94 Only supports dimming 
[Recessed Downlight (RL)](https://www.cooperlighting.com/global/brands/halo/10026198/rl-series) ID = 93 Full support for dimming and temp

I think i've been messing too much and avi-on is timing me out for now, will try and grab the rest later.
