### ISSUE TITLE
Trying to get it running

### ISSUE THREAD

**Issue by deadman96385** [oyvindkinsey/avionmqtt#4]
Nice work on this! Saw your comment on my old issue on the original library. Currently running into an issue getting it setup. Currently testing it on a Raspberry pi 3b. I have all the possible Halo Home products so I should be able to help get it fully functional

```python -m avionmqtt -s settings.yaml 
avion: Fetching devices
mqtt: Connecting to broker
exclude
None
mqtt: Done
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /home/deadman/.local/lib/python3.11/site-packages/aiorun.py:209> exception=TypeError("argument of type 'NoneType' is not iterable")>
Traceback (most recent call last):
  File "/home/deadman/.local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/home/deadman/.local/lib/python3.11/site-packages/avionmqtt/__init__.py", line 361, in main
    await mqtt_register_lights(settings, location, mqtt)
  File "/home/deadman/.local/lib/python3.11/site-packages/avionmqtt/__init__.py", line 148, in mqtt_register_lights
    await mqtt_register_category(settings["groups"], location["groups"], mqtt)
  File "/home/deadman/.local/lib/python3.11/site-packages/avionmqtt/__init__.py", line 143, in mqtt_register_category
    if (include is not None and pid in include) or pid not in exclude:
                                                   ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable```

**Comment by oyvindkinsey** [comment]
It looks like it's not liking your settings, what does your look like?

**Comment by oyvindkinsey** [comment]
Specifically, exclude seems to be set to something other than a list - if not in use, simply remove this from the yaml

**Comment by deadman96385** [comment]
Nice yeah it was, didn't realize empty ones weren't allowed, removed those and it can hook up to the mesh it seems and I see the devices in the mqtt broker. But my log is spammed with the following and HA can't control the lights.

```
mesh: scanning for devices
mesh: Error connecting to device
mesh: Done
```
and repeat over and over

**Comment by oyvindkinsey** [comment]
Are you able to scan for devices using bluetoothctl or similar? What kind of bt interface du you have?

**Comment by oyvindkinsey** [comment]
From the code, that error would suggest not being able to scan for devices, so maybe the Bluetooth service isn't started, or the device driver not properly loaded. 

Would probably be good to handle errors like these a bit more gracefully.

**Comment by deadman96385** [comment]
Yeah you are 100% correct, debugging why I don't have Bluetooth on a fresh Raspbian install right now and will let you know once i get that working

**Comment by deadman96385** [comment]
So I installed raspberrypi-sys-mods, and switched to a proper power supply for it and it seems to work now. My existing mesh is showing up now and HA can control it!!!

**Comment by oyvindkinsey** [comment]
I'll be adding more details on how I have it set up later. It's running as a service, and I have sun automations updating the temperature for the entire mesh. Avi-on's app and API doesn't let you set the temperature without also turning the lights on (iirc), but this does.

**Comment by deadman96385** [comment]
Very nice, Yeah I'll work on getting the rest of my various products added to the mesh so we can get that documented in the implemtation and working properly. I don't expect it to be very hard.
