### ISSUE TITLE
Creates separate MQTT entities under HA instead of a sub device under a avionmqtt device

### ISSUE THREAD

**Issue by niharmehta** [oyvindkinsey/avionmqtt#7]
Currently loads each light and as a separate MQTT device within the MQTT integrations.  It would make it more readable to have a 'avionmqtt' device and each light and group under a light or switch entity.

**Comment by oyvindkinsey** [comment]
I think you need to have it this way in order to be able to place devices in areas etc, and since various automations and components expects lights to be modeled like this. This also mirrors how other integrations like hue does it, making the lights consistent and somewhat interchangeable.

You can relatively easily change this though with how we register the entities, so please test this out first and submit a PR for an optional configuration. 

Avi-on switches unfortunately don't behave as regular switches, and does not have state. They're simply controllers directly affecting the mesh.

**Comment by niharmehta** [comment]
It seems there is a setting within other MQTT entities that you can select a different area than the device area.  When I select the entity, I can disable the option to use the device area and select a new area for the entity. (see attached). 

With avi-on, if the bridge does not keep state, is there a scan function to poll current state from the devices? 
<img width="556" alt="Screenshot 2024-12-10 at 3 03 53 PM" src="https://github.com/user-attachments/assets/e545c942-4d13-481c-b8bf-24af0506d31d">

**Comment by oyvindkinsey** [comment]
The bridge relays updates from the mesh as they come in, and will (after the very recent update) update HA again when HA restarts etc.

Lights are *generally* modeled as individual devices, so I'm curious what you see as the benefit of using one device with multiple entities?

**Comment by niharmehta** [comment]
I don't think its critical to have the bridge periodically poll the mesh. I have seen the mesh status go out of sync with the app in the past, but I assume it was an app issue.  If the bridge is always listening, then I hope if using a separate  controller  such as avi-on bridge, scene-controllers, or  app making change, the avionmqtt bridge will pick up the change triggered by the other controllers.  
It may be useful for the avionmqtt bridge to trigger a poll each time it reconnects to the MQTT server such as if the server restarts, but the avionmqtt bridge process does not restart. 

I understand the lights are generally individual devices, the basic issue is that when you have >50 lights it becomes a bit messy within the MQTT integrations view. Not a huge issue, but ultimately the question is if the light the device, or the bridge is the effective device with each light and group being an entity.  Since each physical light device only presents  a single light entity to control, then it may make more sense to have it be an entity of the avionbridge device. 

I have other MQTT devices that present various controls and sensors as individual entities within the device. It is pretty clear the relationship of the entity to the main device. 

Not knowing the entire Avi-On ecosystem, would this break something else?

**Comment by oyvindkinsey** [comment]
I have > 100 devices, and the main solution to the number is to enable `exclude_in_group`, which means that if a device is in a group, only the group is imported, not the individual lights. That has brought it down to about 30+ total devices, which is quite manageable.
Note that devices and entities can not be used in the same ways across HA.

>  Since each physical light device only presents a single light entity to control, then it may make more sense to have it be an entity of the avionbridge device.

> I have other MQTT devices that present various controls and sensors as individual entities within the device.

I understand, but I don't see the bridge as being a device in and of itself here, it is merely a proxy. 

> Not knowing the entire Avi-On ecosystem, would this break something else?

I wouldn't know what it would break, but I would recommend you look at how lights are generally modeled in HA, as that is what I'm aligning with here.  If you can show that a different model is prevalent, and that the tradeoffs are in favor of changing, then I'm happy to evaluate a PR.

**Comment by oyvindkinsey** [comment]
Since it's actually trivial to do, I'll make this a setting and you can
test it out.

**Comment by oyvindkinsey** [comment]
072642281c486fea4721143b4646e86744428e16 adds on-demand polling via mqtt. This is not documented, as I'll likely add more intelligent logic for getting the updates - for a large mesh, I think there's a chance of some loss during the burst updates, so might do this group by group etc instead.
I also plan to do this on a timer, together with time keeping duties.

b228320197e4bc2e2cd5bfbb33610e28e2f1a10f adds a single_device setting, letting you create a single device instead. After testing this out, I *could* be convinced this is the better default...

**Comment by niharmehta** [comment]
Reopening since there is some activity here. 
I am testing single device controls. So far, its fulfilling my sense of order within the MQTT devices . I have not seen a downside yet, other some oddity in the HA UI where some of the entities show up a a toggle button , and others with the power/ no-power lightning icons next to it. WHen I select on of those icons, it disappears and becomes the toggle .  Seems like a UI issue on how HA automatically tries to create the icons/controls for an enttity.   I can of course click on the bulb and it allows me color and brightness control as well.

**Comment by oyvindkinsey** [comment]
Can we close this now?
I've seen the same issue with the toggles - I suspect this happens when HA doesn't get an explicit state update, as this seems to reset once you interact with it. This again I suspect is because the mesh is flooded with updates at startup, and  some of the messages might be lost - hoping to adopt a different strategy here to avoid this.

**Comment by niharmehta** [comment]
Yes.. I will close this.  The Controls entity list within the MQTT device is my preferred and its working well.  The triggered polling is a nice feature added. Although it seems rare for the state to be out of sync, it is nice to have an option to trigger a poll of the entire mesh .
