### ISSUE TITLE
AVI-ON tunable lights are not colored or dimmable light entities

### ISSUE THREAD

**Issue by niharmehta** [oyvindkinsey/avionmqtt#8]
When imported, individual lights come in to HA as  On/Off and not dimmable, nor can color temp be selected. However, groups are presented correctly with the group dimming and color temp settings

**Comment by oyvindkinsey** [comment]
Do you know what lights you have? 

We need to add the respective products to https://github.com/oyvindkinsey/avionmqtt/blob/c1e42af5e31b8993c86cee50f65fc6e001584446/src/avionmqtt/__init__.py#L22 with their respective capabilities. 
Feel free to submit a PR, or I can make the necessary changes in the morning!

**Comment by oyvindkinsey** [comment]
@niharmehta, are you able to test with a locally modified version, or do you want to wait until I add support for overriding this via the settings?

**Comment by niharmehta** [comment]
I don't think I am getting a product_id from from the devices. Other than the serial number, and the name I set in the app, I do not see an identifier I can set the capabilities on the model # of the devices I am using. Here is a sample output from: MQTT:

`{"component": "light", "object_id": "avid_33403", "unique_id": "2f4e248188e9937060bdbea0", "schema": "json", "payload_off": "OFF", "payload_on": "ON", "brightness": false, "color_mode": false, "effect": false, "retain": true, "state_topic": "hmd/light/avid/33403/state", "json_attributes_topic": "hmd/light/avid/33403/attributes", "command_topic": "hmd/light/avid/33403/command", "device": {"identifiers": ["2f4e248188e9937060bdbea0"], "name": "AmpC", "manufacturer": "Avi-on", "model": "Unknown", "serial_number": "2f4e248188e9937060bdbea0"}}`

The model I am using are the Halo Home: BLD6089BLE40AWH
https://www.cooperlighting.com/global/brands/halo-home/1053911/halo-home-smart-surface-mount-downlight-bld6

**Comment by oyvindkinsey** [comment]
Once https://pypi.org/project/avionmqtt/ updates to 1.3.6, you can update and the product_id will be added to the device name.

But the simplest way by far is to simply enumerate the devices using https://github.com/oyvindkinsey/avionmqtt/blob/v1.3.6/resources/Reverse%20engineering.md#interactive-exploration-of-their-apis
There you'll find product ids, while you can get the official names by looking at the device on https://myaccount.avi-on.com/

**Comment by niharmehta** [comment]
tested with 1.3.6 and saw that it now has the ID number in the description.  Tested changes seem to work now , so PR created.

**Comment by oyvindkinsey** [comment]
Also added support overriding the capabilities via settings.yaml in d08414f582211381d7801249b69b0879ce3567d2
